### ISSUE TITLE
Update foundry v10

### ISSUE THREAD

**Issue by Landarel** [superseva/talisman#11]
Hallo, 

I wantee to ask if there will be an update to foundrys latent Version v10?

I would be very happy about that, but i couldn't find a hint if yes or not. So i as this question here. I hope that is not inapropriate. 

Best wishes

Landarel

**Comment by superseva** [comment]
Hi, unfortunately I have no plans of updating the system to newer version soon. Maybe after the holidays I'll find some time to get back to it and update it.
The amount of changes Foundry makes from version to version is just to big for so little free time I have ;(

**Comment by Landarel** [comment]
That is sad but absolutley understandable 😔 thank you very much for your Quick reply. 

Maby you find some time later but if Not it is fine 🙂

Have a nice time and happy hollydays by then
