### ISSUE TITLE
Error checking for new updates

### ISSUE THREAD

**Issue by MadGM** [superseva/talisman#14]
When Updating Talisman under Game Systems the following error is giving, "The requested manifest at "https//raw.githubusercontent.com/superseva/talisman/releases/latest/download/system.json" did not provide manifest data.
I don't think there is an more current update, but when I update all it spits out that error message

**Comment by superseva** [comment]
I'll check it with the Foundry team. 
It might be because talisman was discontinued at one point.
Any how you can just uninstall and install the system again to get the new updates

**Comment by superseva** [comment]
it should be fixed now, but you should probably still re-install. You will not lose any data by doing so.
