### ISSUE TITLE
Followers Tab

### ISSUE THREAD

**Issue by discuit** [superseva/talisman#3]
Is there any way to make this Tab a little more useable at a glance? Perhaps some way of displaying a small text box under each skill allowing for a a brief explanation without having to enter the edit option? No biggy, just a QoL thing. Additionally when the Skill name is too long, it cuts off the description in the Tab screen. Eg. Skillful (Smithing) shows as other | weal. Also when broadcasting to the chat box there seems to be a weird "Tweal" error. See screenshot.
![Follower Error](https://user-images.githubusercontent.com/75380246/100895822-e293e400-34b5-11eb-9056-f26c009c29d7.jpg)

**Comment by superseva** [comment]
yeah, followers need some love regarding UI in general

**Comment by superseva** [comment]
Some UI improvements on follower tab
